# Generated by Django 5.1.3 on 2024-12-06 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
