# Generated by Django 5.1.3 on 2024-12-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
