# Generated by Django 5.1.3 on 2024-12-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_unique_id", models.IntegerField()),
                ("query_date_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
