# Generated by Django 5.1.3 on 2024-12-05 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PatientID",
        ),
    ]
