# Generated by Django 5.1.3 on 2024-12-06 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctor", "0002_delete_patientid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                ("doctor_id", models.AutoField(primary_key=True, serialize=False)),
                ("phone_number", models.CharField(max_length=15)),
                ("NMC_registered_number", models.CharField(max_length=50, unique=True)),
                ("address", models.TextField()),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("availability_status", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
