# Generated by Django 5.1.3 on 2024-11-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("STUDENT", "Student"),
                    ("TEACHER", "Teacher"),
                ],
                default="STUDENT",
                max_length=40,
            ),
            preserve_default=False,
        ),
    ]
