# Generated by Django 5.1.3 on 2024-12-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0002_myuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="teacherprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
        migrations.AlterField(
            model_name="myuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("DOCTOR", "Doctor"),
                    ("PATIENT", "Patient"),
                ],
                max_length=40,
            ),
        ),
        migrations.DeleteModel(
            name="StudentProfile",
        ),
        migrations.DeleteModel(
            name="TeacherProfile",
        ),
    ]
