# Generated by Django 5.1.3 on 2024-12-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0003_remove_studentprofile_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("DOCTOR", "Doctor"),
                    ("PATIENT", "Patient"),
                ],
                default="PATIENT",
                max_length=40,
            ),
        ),
    ]
