# Generated by Django 5.1.3 on 2024-12-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0004_alter_myuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="profilepicture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
